### ISSUE TITLE
Go to KielHack 2014

### ISSUE THREAD

**Issue by neonichu** [neonichu/life#16]
Date: 04. - 06. Juli 2014 
See http://kiel.stadthack.de
- Contentful sponsors, so I need prepare something for the kickoff
- Maybe even a Contentful-themed project for me to pitch
- [x] Train (should be paid by Contentful)
- [x] Accommodation (ask @hbehrens, I guess)
- [ ] Event itself
- [ ] Documentation
- [ ] Retro

**Comment by HBehrens** [comment]
jup, just ask @hbehrens
